### ISSUE TITLE
Content-Type header is being set for DELETE request, fails with fastify

### ISSUE THREAD

**Issue by rahulbhanushali** [zachrybaker/ra-data-rest-client#1]
On deleting a resource, the HTTP request generated set the 'content-type: application/json' header.
This results in error since the request body is empty. Not sure about other frameworks but fastify throws an error with below message:

`{"statusCode":400,"code":"FST_ERR_CTP_EMPTY_JSON_BODY","error":"Bad Request","message":"Body cannot be empty when content-type is set to 'application/json'"}`

**Comment by rahulbhanushali** [comment]
After checking the code realised this is the problem with ra-data-simple-rest. Have a raised a bug there: https://github.com/marmelab/react-admin/issues/5452

**Comment by zachrybaker** [comment]
Hi @rahulbhanushali,

Once a solution is in pulled into master for [marmelab/react-admin/issues/5452](https://github.com/marmelab/react-admin/issues/5452) I'll pull it in.  Feel free to nudge if I don't immediately notice.

**Comment by zachrybaker** [comment]
PR when they fix, I'll pull.
